### ISSUE TITLE
Is ERC20 support production ready?

### ISSUE THREAD

**Issue by elie222** [loomnetwork/plasma-cash#117]
When will ERC20 support be announced?

**Comment by gakonst** [comment]
This was merged 2 weeks ago https://github.com/loomnetwork/plasma-cash/pull/83

**Comment by elie222** [comment]
Thanks. What I saw online about it was that it was yet to be released. Not sure if an official announcement was yet made about it, or if in the Loom docs.

**Comment by elie222** [comment]
https://loomx.io/developers/docs/en/transfer-gateway.html

Currently only ERC721 tokens are supported, but support for ERC20 tokens, and ETH will be added in the near future.
