### ISSUE TITLE
ERC20/Eth splitting and merging

### ISSUE THREAD

**Issue by elie222** [loomnetwork/plasma-cash#118]
This article mentions token splitting and merging:
https://medium.com/loom-network/plasma-cash-initial-release-plasma-backed-nfts-now-available-on-loom-network-sidechains-37976d0cfccd
> Next Steps — Token Splitting and Merging
> Our next steps are to add support for ERC20 tokens and ETH.

Now that Plasma Cash for ETH, ERC20 has been released, does it support token splitting/merging?

**Comment by gakonst** [comment]
We've been discussing Merging & Splitting for a while, I do not have a clear design for it. This thread from ethresear.ch may provide you some guidance https://ethresear.ch/t/one-proposal-for-plasma-cash-with-coin-splitting-and-merging/1447

With regards to supporting arbitrary denomination payments with ETH/ERC20 tokens, I'm prototyping a construction called Plasma Debit https://ethresear.ch/t/plasma-debit-arbitrary-denomination-payments-in-plasma-cash/2198. This is still not finalized neither has a spec so it's all very experimental at the moment. I have an open PR that will address this eventually https://github.com/loomnetwork/plasma-cash/pull/115

**Comment by gakonst** [comment]
Closing, feel free to reopen if there's further questions on this matter
