### ISSUE TITLE
What prevents double spends? 

### ISSUE THREAD

**Issue by elie222** [loomnetwork/plasma-cash#119]
If Alice decides to send the same signed tx to both Bob and Charlie, what determines which one goes through?
Is the first one that's settled on the main chain? 
Does the side chain have to make periodic updates to the main chain? And if so doesn't that hurt the speed of transactions on the side chain?

**Comment by elie222** [comment]
This step in the Readme seems to be the relevant one:

Operator calls submitBlock, checkpointing the block merkle root which includes the transaction that gives ownership to charlie. At this point, both the child chain and the root chain, have checkpointed alice's transaction at block number 1000.

But if we have to submit to mainnet on each transaction, don't we lose the speed benefits of using a child chain?

**Comment by gakonst** [comment]
The whole point of Plasma is that every plasma block gets submitted to the main chain. The double spend cases are covered by `challengeBetween`, https://github.com/loomnetwork/plasma-cash/blob/master/server/test/testChallengeBetween.js. More details here https://karl.tech/plasma-cash-simple-spec/

Plasma does not improve finality. A transaction can be considered finalized after a plasma block root which includes it has been committed to the contract (+some block buffer for potential reorgs, but you parameterize accordingly). Plasma improves throughput/capacity by allowing many transactions of a potentially huge plasma block be finalized in 1 onchain tx. it is closer to a compression mechanism that allows more transactions to settle per block slot, 15s in Ethereum

**Comment by elie222** [comment]
Thanks. Understood.

How often is the sidechain expected to commit blocks to the main chain?

I realise there's no correct answer here. If there are 100txs per second I
take it that it makes sense for the operator to submit a block every 15
seconds? If the sidechain is less popular then perhaps every few minutes?

On 26 Aug 2018 11:06, "Georgios Konstantopoulos" <notifications@github.com>
wrote:

The whole point of Plasma is that every plasma block gets submitted to the
main chain. The double spend cases are covered by challengeBetween,
https://github.com/loomnetwork/plasma-cash/blob/master/server/test/testChallengeBetween.js.
More details here https://karl.tech/plasma-cash-simple-spec/

Plasma does not improve finality. A transaction can be considered finalized
after a plasma block root which includes it has been committed to the
contract (+some block buffer for potential reorgs, but you parameterize
accordingly). Plasma improves throughput/capacity by allowing many
transactions of a potentially huge plasma block be finalized in 1 onchain
tx. it is closer to a compression mechanism that allows more transactions
to settle per block slot, 15s in Ethereum

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/loomnetwork/plasma-cash/issues/119#issuecomment-416021613>,
or mute the thread

**Comment by gakonst** [comment]
Closing since the discussion moved in https://ethresear.ch/t/plasma-chain-block-times/3092/. Ideally we should aim for 15s times, but what you say is possible, it's just another parameter of the system
