### ISSUE TITLE
Installation issues with python3.6.5

### ISSUE THREAD

**Issue by hemulin** [loomnetwork/plasma-cash#122]
Running on Lubuntu 16.04.

The latest common python3.6 release is `3.6.5`.

Running `pip install -r requirements.txt` results in: 
```
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Searching online shows that this error is related specifically to 3.6.5.

---

Updating python minor version (manually compiling 3.6.6 from source) resolved this and allowed pip install to run its course.
There was still a warning:
```
eth-utils 1.2.1 has requirement eth-typing<2.0.0,>=1.3.0, but you'll have eth-typing 2.0.0 which is incompatible
```
But perhaps one can ignore it in the meantime.

**Comment by bobio2018** [comment]
confirm I have seen eth-utils error on MacOSX as well
```eth-utils 1.2.2 has requirement eth-typing<2.0.0,>=1.3.0, but you'll have eth-typing 2.0.0 which is incompatible.```
but I didn't see the first error
