### ISSUE TITLE
The path /usr/bin/python3.6 (from --python=/usr/bin/python3.6) does not exist

### ISSUE THREAD

**Issue by bobio2018** [loomnetwork/plasma-cash#128]
This is NOT possible to install python3 into /usr/bin/python3.x on Mac OS X El Capitan anymore as from then on System Integrity Protection prevents that.

my solution is to use the library frameworks path

```
$ which python3
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3
```

then run below

```
mkvirtualenv erc721plasma --python=/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
```

**Comment by gakonst** [comment]
Closing as python is no longer in the repo
