### ISSUE TITLE
[Question]Users have to be online once a half week?

### ISSUE THREAD

**Issue by syuhei176** [loomnetwork/plasma-cash#149]
Hi, I have a question about implementation about invalid history challenge.

I think users have to be online once a week in Plasma Cash.

But it seems like that users have to be online once a half week in this implementation. Is it right?
https://github.com/loomnetwork/plasma-cash/blob/master/server/contracts/Core/RootChain.sol#L644

**Comment by gakonst** [comment]
We split the challenge period for challenges with invalid history to avoid an attack where an interactive challenge is made right before the challenge period is over and there is no way to respond to it. The full 7 days can be used for non-interactive challenges. The 7 days is just a security parameter and you can adjust it in whatever way you like.

**Comment by syuhei176** [comment]
Thank you for your replying! I understood.

This is just a question.
Extending "respondChallenge period" when challengeBefore occurred is not good implementation?
